parameters:
#    glutzic_calculator.example.class: Glutzic\CalculatorBundle\Example

services:
#    glutzic_calculator.example:
#        class: %glutzic_calculator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
